basePath: /
definitions:
  dto.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        maxLength: 50
        minLength: 3
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  util.ErrorBody:
    properties:
      error: {}
    type: object
info:
  contact: {}
  description: API for managing users and assets in MF Stock Tracker.
  title: MF Stock Tracker API
  version: "1.0"
paths:
  /api/users:
    delete:
      description: Delete user by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorBody'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorBody'
      security:
      - BearerAuth: []
      summary: Delete user
      tags:
      - users
  /api/users/:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: Create user payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorBody'
      summary: Create user
      tags:
      - users
  /api/users/login:
    post:
      consumes:
      - application/json
      description: Authenticate user with email and password
      parameters:
      - description: Login payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorBody'
      summary: User login
      tags:
      - users
  /api/users/verify:
    get:
      description: Verify bearer token and return user info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorBody'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorBody'
      security:
      - BearerAuth: []
      summary: Verify token
      tags:
      - users
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
